### ISSUE TITLE
Storage_diffs missing for state updates from 0 -> any non negative value

### ISSUE THREAD

**Issue by cptartur** [Shard-Labs/starknet-devnet#111]
Invoke transactions sent to devnet that modify contract's storage from initial value of 0 to any non negative value, don't show up as storage_diffs in the result of `get_state_update`.

## Steps to reproduce 
(note hash values will be different than in my example outputs):

1. Deploy any contract with storage to devnet, for example this balance contract
```cairo
# Declare this file as a StarkNet contract.
%lang starknet

from starkware.cairo.common.cairo_builtins import HashBuiltin

# Define a storage variable.
@storage_var
func balance() -> (res : felt):
end

# Increases the balance by the given amount.
@external
func increase_balance{
    syscall_ptr : felt*,
    pedersen_ptr : HashBuiltin*,
    range_check_ptr,
}(amount : felt):
    let (res) = balance.read()
    balance.write(res + amount)
    return ()
end

# Returns the current balance.
@view
func get_balance{
    syscall_ptr : felt*,
    pedersen_ptr : HashBuiltin*,
    range_check_ptr,
}() -> (res : felt):
    let (res) = balance.read()
    return (res)
end
```

2.  Increase the balance 
`starknet invoke --address <address>  --abi balance_abi.json --function increase_balance --inputs 123 --gateway_url <gateway> --feeder_gateway_url <feeder_gateway>`

3. Get the state_diff of the latest block
`starknet get_state_update --block_number latest --gateway_url <gateway> --feeder_gateway_url <feeder_gateway>`

Both deployed_contracts and storage_diffs will be empty, even though storage increased.

```json
{
    "block_hash": "0x1e1523a33336e8f75e69433569672087986a426ff9aad39e05e469b213618c8",
    "new_root": "07c7a16fdf3cac95f94a04ebc2da7e7d8e10496bde6bf4d0143ef560e188ae6f",
    "old_root": "058751f6b6e66e778aec353f0d17720292f7ab70b764e720f11e0de8e93289db",
    "state_diff": {
        "deployed_contracts": [],
        "storage_diffs": {}
    }
}
```

4. Increase the balance again
`starknet invoke --address <address>  --abi balance_abi.json --function increase_balance --inputs 123 --gateway_url <gateway> --feeder_gateway_url <feeder_gateway>`

5. Get the state_diff of the latest block

Storage diffs will now show a value

```json
{
    "block_hash": "0x97caa35c003b4150fb8877916402f503308b9490b51481428967b27897c777",
    "new_root": "011247fe7c8f8ed7b8b34a7e090cb5117dd94412dfafb214eec2120363a14104",
    "old_root": "07c7a16fdf3cac95f94a04ebc2da7e7d8e10496bde6bf4d0143ef560e188ae6f",
    "state_diff": {
        "deployed_contracts": [],
        "storage_diffs": {
            "0x02e3217d5a75f5830c7a89b189c2b0e0622eaf1d066bb2fc7fc2545507576657": [
                {
                    "key": "0x206f38f7e4f15e87567361213c28f235cccdaa1d7fd34c9db1dfe9489c6a091",
                    "value": "0xf6"
                }
            ]
        }
    }
}
```

In the case of my inputs its `0xf6 == 246 == 123 + 123`, so devnet calculates storage correctly, but even though it increased in the first invoke transaction, it was missing from the state diff.

**Comment by badurinantun** [comment]
Thanks for opening the issue, I was able to reproduce it and fix it! Opening PR soon
