### ISSUE TITLE
Not receiving ACCEPTED_ON_L2 transaction on devnet

### ISSUE THREAD

**Issue by ccarnino** [Shard-Labs/starknet-devnet#114]
I am using the useStarknetTransactionManager() react hook and logging to console the transactions received.

When I point to devnet, I don't receive the transaction for the `ACCEPTED_ON_L2`. I am just receiving the `TRANSACTION_RECEIVED` transaction. 
But, when I point to alpha I receive the `ACCEPTED_ON_L2` transaction as expected.

Why on devnet don't I receive the other transaction events?

**Comment by FabijanC** [comment]
This looks like a starknet-react issue. Have you tried searching or asking there? https://github.com/apibara/starknet-react/issues

**Comment by ccarnino** [comment]
Thanks Fabian, but they suggested me it was a devnet issue https://discord.com/channels/793094838509764618/950372319119937606/978758555391897690

**Comment by ccarnino** [comment]
I've also not found any issue regarding this on neither `starknet.js` nor `starknet-react` repos

**Comment by FabijanC** [comment]
So, the issue is somehow related to `useStarknetTransactionManager`? What is that / what does it do? Also, you mention receiving "transaction for the `ACCEPTED_ON_L2`" and `TRANSACTION_RECEIVED` transaction. Do you mean response? Also, later on you are mentioning events, are you really referring to events?

**Comment by ccarnino** [comment]
`useStarknetTransactionManager` is simply an ReactJS function that calls a callback when there are updates regarding transactions started from the wallet.

So when I use it on alpha, I receive transaction with status like `TRANSACTION_RECEIVED, PENDING, ACCEPTED_ON_L2` etc.
But when I use it on devnet, I only receive transaction with status `TRANSACTION_RECEIVED`.

Why is this difference?

Here `starknet.js` (which is what `starknet-react` is built on top of) list of transaction statuses
https://github.com/0xs34n/starknet.js/blob/5374fdf676915d634775c7c072ea923ddaee2817/www/docs/API/provider.md#gettransactionstatusresponse

**Comment by ccarnino** [comment]
I noticed that the transactions where actually ACCEPTED_ON_L2. So after testing and debugging, it turns out I was only listening for the first transaction status update. If I "listened" for the next ones, I would also received ACCEPTED_ON_L2.

So, devnet and all the libraries are working as expected. It was my fault. 
Thanks for the help anyway!
