### ISSUE TITLE
Mint devnet eth??

### ISSUE THREAD

**Issue by ccarnino** [Shard-Labs/starknet-devnet#122]
Hello team.
ArgentX updated with mandatory fee. So while running my own app against devnet, I now need some eth to pay for transactions.

How can I mint some eth for my wallet?
Thanks!

**Comment by FabijanC** [comment]
Currently it cannot be done, but future versions will support it - maybe even the next version (after 0.2.2).

**Comment by FabijanC** [comment]
@ccarnino not coming in the next version (0.2.3), but the one after

**Comment by ccarnino** [comment]
Does it mean that the only way to keep working with devnet is to install the old version of ArgentX wallet?

**Comment by FabijanC** [comment]
Probably, but hopefully only for a few days, really hope to have a version supporting this next week.

**Comment by janek26** [comment]
Let me know as soon as this feature exists @FabijanC and I'll make sure it gets a place inside of Argent X in case the devnet is selected :-)

**Comment by janek26** [comment]
@FabijanC no worries! Already saw it and somebody else from your team already reached out aswell 👀

**Comment by ccarnino** [comment]
@FabijanC @janek26 I am still stuck that as a user on devnet I cannot pay for transactions since I don't have eth. How do I solve this?

Is ArgentX planning to allow me to 1. mint some ETH, or 2. add a pretended account to the wallet via private key?
