### ISSUE TITLE
New release for Cairo 0.9.0 support?

### ISSUE THREAD

**Issue by ca11ab1e** [Shard-Labs/starknet-devnet#123]
Hey there,

Do you have an approximate date for a new release with the 0.9.0 Cairo support?

**Comment by FabijanC** [comment]
Hopefully this week. You can also run from source: [instructions](https://github.com/Shard-Labs/starknet-devnet#development). The current version on the `master` branch already has the majority of the features implemented (everything except contract class declarations).

**Comment by ca11ab1e** [comment]
Great, thanks :)
