### ISSUE TITLE
Update open zeppelin account contracts

### ISSUE THREAD

**Issue by janek26** [Shard-Labs/starknet-devnet#128]
The contract code for account contracts is 2 month old :) Couple of things have changed since then, can we please make sure to pull in the latest version of https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/openzeppelin/account/Account.cairo ?

Blocking starknet.js tests

**Comment by FabijanC** [comment]
I thought we are using the latest released version (v0.1.0): https://github.com/OpenZeppelin/cairo-contracts/releases
And I saw a recommendation on Discord not to use the latest version from the main branch, if that's what you mean.

**Comment by janek26** [comment]
Latest version from main is fine, and it's de facto what's deployed everywhere else :) 
I think you should update to it, or provide a possibility for the devnet user to provide his own account contract Cairo file which then gets used as the redeployed accounts
