### ISSUE TITLE
Got ClientConnectorCertificateError while trying to access https://alpha4.starknet.io/gateway/add_transaction

### ISSUE THREAD

**Issue by qkaver** [Shard-Labs/starknet-devnet#130]
when i deploy using localhost it's ok, but failed in goerli, and how can i choose the devnet?
 --network localhost
🚀 Deploying ERC721
⏳ ️Deployment of ERC721 successfully sent at 0x0632bcc92835bb37b71c82fee273c966d0863134e4f1e2c2184dc8cb4713a7a1
🧾 Transaction hash: 0x17275a2d05f67778c1f0434b6b1b21e7a5d893c6904a10e6da50e779e819954
📦 Registering 0x0632bcc92835bb37b71c82fee273c966d0863134e4f1e2c2184dc8cb4713a7a1 in 127.0.0.1.deployments.txt
(env) (base) MacBook-Pro:starknet qkaver$ nile deploy ERC721 6001127147006152263 21336 2689760648704244976701818254133193310968075258309729491871695171359883455256 --network goerli
🚀 Deploying ERC721
Got ClientConnectorCertificateError while trying to access https://alpha4.starknet.io/gateway/add_transaction.
Error: ClientConnectorCertificateError: Cannot connect to host alpha4.starknet.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]

**Comment by FabijanC** [comment]
This is a nile issue, ask there: https://github.com/OpenZeppelin/nile/issues
