### ISSUE TITLE
No transaction created for l1 -> l2 transactions

### ISSUE THREAD

**Issue by charlietilt** [Shard-Labs/starknet-devnet#141]
## Summary
For l1 ->2 bridge transactions, the state changes are not yielding a new transaction/block.

## General steps to reproduce
1) Create contract on l1 with a function to send a message to l2 `sendMessageToL2`
2) Create a contract on l2 with a `@l1_handler` to consume the message
3) In the l2 contract update the state in some way

**Comment by FabijanC** [comment]
Is the behavior the same if you are using alpha-goerli instead of starknet-devnet?

**Comment by FabijanC** [comment]
Any progress? @charlietilt

**Comment by charlietilt** [comment]
@FabijanC, I have confirmed that it is working correctly on alpha-goerli.
When bridging items from l1->l2 on devnet neither blocks nor transactions are not getting created.

**Comment by mikiw** [comment]
Confirmed, after L1>L2 call new transaction is not generated.

**Comment by mikiw** [comment]
TODO:
1. Check how this scenario works on Alpha Goerli.
2. Check how L1L2 mechanism was implemented in starknet-devnet, this is first PR of that feature - https://github.com/Shard-Labs/starknet-devnet/pull/36/files
3. Replicate that behaviour from Alpha Goerli.
