### ISSUE TITLE
Issue with `increase_time` and `set_time` RPC endpoint

### ISSUE THREAD

**Issue by johnson2427** [Shard-Labs/starknet-devnet#144]
**Describe the bug**

When using the RPC endpoint, if the new timestamp is called, there is no change to the timestamp value

```python
current_timestamp = # Code to get timestamp here
response = requests.post(url=f"{self.uri}/increase_time", json={"time": seconds_to_increase})
new_timestamp = # Code to get timestamp here again
new_timestamp - current_timestamp != seconds_to_increase
```
### Not a great example, but this is embedded in a python class, using Ape. My example wouldn't make sense

**Not reproducible on alpha-goerli**
- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli.

**To Reproduce**
1. Start a local devnet testnet
2. get timestamp
3. set the timestamp with a post request to /increase_time or /set_time
4. get timestamp again
5. old and new timestamp will be equal

**Expected behavior**

You would expect the new timestamp to be greater than the old timestamp

**Devnet version**
- I am using Devnet version: 0.2.4
- This does not appear on the following Devnet version: Unknown

**Machine specifications**
- OS: Ubuntu 20.04
- CPU: AMD Ryzen 9 5950x 16-core processor x 32
- Memory: 64GB DDR4

**Comment by FabijanC** [comment]
This is what the documentation reads:

> ## Set time
> Sets the exact time of the **next generated block**. All subsequent blocks will keep the set offset.

> ## Increase time
> Increases the time offset for **each generated block**.

So the changes are applied for the newly generated blocks.

**Comment by johnson2427** [comment]
@FabijanC thank you for your quick response! I am performing this on a pending block, so I believe these should still be applicable. Although, maybe I'm mistaken?
