### ISSUE TITLE
Build Docker image in parallel

### ISSUE THREAD

**Issue by ivpavici** [Shard-Labs/starknet-devnet#159]
Devnet docker image could be built in parallel with tests, then in the publish job it could just be pushed - right now the building needs to wait for tests to finish

Not sure if this can actually be done, i.e. if the built image will be preserved for other circleci steps/jobs

**Comment by FabijanC** [comment]
This can be done by combining with #160:
- an image with an appropriate tag (candidates: `next`, `beta`, `master`) could be built on each push to master (regardless of a new version being released) - this could be done in a separate job running in parallel with tests
- the current `image build and push` would just do the pushing (and only on the master branch when:
  - first it would fetch the image tagged with `next`, then it give it the official tag, then it would push
