### ISSUE TITLE
Allow specifying how blocks are constructed

### ISSUE THREAD

**Issue by ivpavici** [Shard-Labs/starknet-devnet#163]
Block construction might add a lot to total execution time of calls and invokes. Yet, it might be that blocks aren't needed by developers that often. Therefore, an option like --no-block  or --no-blocks could be added, which would do everything that Devnet does, but without block generation. Or more generally, something like --block <SIZE> could be provided to indicate how often blocks are generated, i.e. after how many transactions.

**Comment by EvolveArt** [comment]
Highly supportive of that change. In my case it would prevent me from fetching the current block timestamp multiple times in one test. Also I'm running tests that require the block not to change to work, otherwise an `update` function has to be called. This option would totally solve it so **+1**

**Comment by maciejka** [comment]
Another option would be to generate block on request
