### ISSUE TITLE
Unable to use web3.py to work with Ethereum when starknet-devnet is installed in same env

### ISSUE THREAD

**Issue by unparalleled-js** [Shard-Labs/starknet-devnet#168]
**Describe the bug**
In projects that use both Ethereum and Starknet, we need web3.py to facilitate deploying Ethereum transactions.
However, we are running into eth-abi encoding issues regarding address arguments to the transactions.
We notice that this only occurs when starknet-devnet is installed. When starknet-devnet is uninstalled, the transactions work as expected. Otherwise, we are unable to pass addresses as arguments to them.

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

* Install starknet-devnet
* Use web3.py to connect to Ethereum and deploy a txn
* Notice address encoding errors
* Nothing starknet is actually used, just installed

**Expected behavior**

Able to still use Ethereum when starknet-devnet is installed

**Screenshots**
If applicable, add screenshots to help explain your problem. However, prefer providing copyable text.

**Devnet version**

- I am using Devnet version:
- [x] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**Machine specifications**

- OS: macOS
- CPU:
- Memory:

**Comment by ca11ab1e** [comment]
Finally fixed here:

- https://github.com/ApeWorX/ape-starknet/pull/66

**Comment by FabijanC** [comment]
@ca11ab1e Fixed in what sense? This was an issue on your side?

**Comment by ca11ab1e** [comment]
Yes, it was an issue on my side.

@unparalleled-js should confirm, but the issue was that as soon as `ape-starknet` was installed, it was being used for non-Starknet stuff. For instance Ape was trying to decode Solidity contract addresses using the Starknet-specific function.
If I'm right, and not off-topic, that's not a devnet issue.
