### ISSUE TITLE
Mainnet forking

### ISSUE THREAD

**Issue by fracek** [Shard-Labs/starknet-devnet#18]
As I mentioned in the community call last week, it would be amazing to have mainnet forking. The use case it's to test how our dapp interacts with existing dapps deployed to the network. I know that now it's not possible to implement this, so this is more of a question to know what is needed to make this happen?

**Comment by FabijanC** [comment]
Thanks once again for the proposal. I'm sharing this issue to more places.

**Comment by 0xSidius** [comment]
Any updates on this important feature? @FabijanC

**Comment by FabijanC** [comment]
> Any updates on this important feature? @FabijanC

I agree that it is important. It is in plans to be done, but not in the very near future.

**Comment by 0xSidius** [comment]
> On hold until: "_we have an independent Cairo VM + a StarkNet runner with a more lenient API (I'm guessing that this will be available in O(3 months))._"

do you plan to use the Cleopatra VM (rust) ?

**Comment by ivpavici** [comment]
Hi @0xSidius ! Could you give more insight how using Cleopatra on our side would help with forking?

**Comment by 0xSidius** [comment]
> Hi @0xSidius ! Could you give more insight how using Cleopatra on our side would help with forking?

it wouldn't w.r.t. to forking, but it could significantly improve DevEx, cutting down the current main Starknet bottleneck (performance)

Did you take a hard look at developer experience today on Starknet? Even a modest project, using the fastest toolchains (Protostar) with Devnet will see hours-long test runs
