### ISSUE TITLE
Suggestion: Add an endpoint for returning the feeToken address

### ISSUE THREAD

**Issue by amanusk** [Shard-Labs/starknet-devnet#190]
Although my understanding is that the fee token shouldn't be changed in the future, it might be useful to have an endpoint that returns it, instead of relying on a hard coded value.

Users (e.g. hardhat-plugin) can then query the feeToken and run tests on fees used etc, without worrying about changes to the feeToken on newer versions

**Comment by FabijanC** [comment]
Thanks for the suggestion, sounds like a reasonable idea.

**Comment by amanusk** [comment]
I can trying making a PR :)

**Comment by FabijanC** [comment]
Please do!
