### ISSUE TITLE
Error: Installing startnet-devnet on Windows

### ISSUE THREAD

**Issue by prajwal27** [Shard-Labs/starknet-devnet#191]
**Describe the bug**
I get this bug when I run the command `pip install starknet-devnet`

![image](https://user-images.githubusercontent.com/31249460/180617846-0f0b8806-9c87-4472-a919-52afeb93197f.png)

**Machine specifications**

- OS: Windows
- CPU: I5 ( Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~2500 Mhz)
- Memory: 16GB RAM

**Comment by tabaktoni** [comment]
Thank you for report,
Officially we do not support Windows at the moment, but on windows, you can use WSL2.

1. install docker / enable wsl2
2. download terminal and ubuntu from the store
3. sudo apt update
4. sudo apt install software-properties-common
5. sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.7
sudo apt install python3-pip7

sudo pip3 install virtualenv 
virtualenv venv 
source venv/bin/activate

sudo apt install -y libgmp3-dev
pip3 install cairo-lang

If all these steps pass then you could do also starknet-devnet install.
Please give us feedback on your progress.

**Comment by tabaktoni** [comment]
Another approach is also to try to run the dockerized version, it could be easier than the native run. Follow readme for Docker.

**Comment by ivpavici** [comment]
We will write a tutorial on how to setup devnet on Windows using WSL2

**Comment by FabijanC** [comment]
@ivpavici It should just be enough to mention that, on Windows, options include Docker and WSL2

**Comment by ivpavici** [comment]
Tutorial written:
https://medium.com/spaceshard/how-to-run-starknet-devnet-on-windows-tech-tutorial-f8447c131193
