### ISSUE TITLE
Test RPC `add_deploy_transaction` with `constructor_calldata != []`

### ISSUE THREAD

**Issue by cptartur** [Shard-Labs/starknet-devnet#198]
Contract currently used in RPC deploy transaction test currently does not accept any constructor_calldata, which means we are not testing if we are correctly parsing passed calldata. This should be improved by either changing contract used in these tests or adding a separate tests using different contract with nonempty constructor parameters.

**Comment by internnos** [comment]
i'm planning to handle this issue

however, i think that its better to wait until [this pull request](https://github.com/Shard-Labs/starknet-devnet/pull/220) is merged

what do you guys think?

@cptartur

**Comment by ivpavici** [comment]
@internnos yeah, probably would be good to wait first! 
@cptartur, @drknzz is this it ok for @internnos to handle this, I mean it's not covered in the PR?

**Comment by drknzz** [comment]
Yeah, it's not covered in the PR, so I'd say go ahead.

**Comment by internnos** [comment]
cool,

thank you!
