### ISSUE TITLE
Profiling report - performance improvement investigations

### ISSUE THREAD

**Issue by tabaktoni** [Shard-Labs/starknet-devnet#208]
1. **Test Pypy vs cPython**
Measured using werkzeug.middleware.profiler
Calling is_alive and then mint function
- first call after the init is the slowest, consequential calls become faster until a time of 1-2s on average
- async primitive fill thread pool and with each thread aquire thread lock which has the longest time
- potential python GIL lock limitation
- didn't notice a performance boost by pypy at all, sometimes performed even worse
- Replacing Flask with Quart and WSGI with ASGI produces huge performance loss for this test

To swith to pypy first install it on you machine than do [poetry env use pypy](https://python-poetry.org/docs/managing-environments/#switching-between-environments)

[devent-pypy-report.txt](https://github.com/Shard-Labs/starknet-devnet/files/9251578/devent-pypy-report.txt)
[devent-cpy-report.txt](https://github.com/Shard-Labs/starknet-devnet/files/9251580/devent-cpy-report.txt)

2. **cPython cProfiler**
First call /is_alive then consequential /mint run
[devenet-profile-mint.txt](https://github.com/Shard-Labs/starknet-devnet/files/9251753/devenet-profile-mint.txt)
Pofiler Files, can be visualized with 'snakeviz'
[mint-run-1.TXT](https://github.com/Shard-Labs/starknet-devnet/files/9251765/mint-run-1.TXT)
[mint-run-2.TXT](https://github.com/Shard-Labs/starknet-devnet/files/9251766/mint-run-2.TXT)
<img width="1680" alt="Screenshot 2022-08-03 at 14 31 14" src="https://user-images.githubusercontent.com/923054/182621122-eaf67fd5-adff-451e-a1ce-51dd2771a72e.png">

3. **pyinstrument cPithon**
Profile from start of mint call to its end.
[profile-mint-call.TXT](https://github.com/Shard-Labs/starknet-devnet/files/9251818/profile-mint-call.TXT)
Profile from App start to end of mint call:
[devnet-first-call.TXT](https://github.com/Shard-Labs/starknet-devnet/files/9251830/devnet-first-call.TXT)
Rename files to .html and open to see results

**Comment by FabijanC** [comment]
Related: #52

**Comment by Solpatium** [comment]
Minting is relatively light operation. Have you tried using something more computationally intensive?

**Comment by Solpatium** [comment]
>didn't notice a performance boost by pypy at all, sometimes performed even worse
Minting is a relatively light operation. Have you tried using something more computationally intensive? Team working on Cleopatra VM posts benchmarks often and CPython is much slower than PyPy there.
