### ISSUE TITLE
Apply timestamp setting prior to block/transaction creation (not after)

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-devnet#216]
Currently we apply the changes requested by time advancing (https://github.com/Shard-Labs/starknet-devnet#advancing-time) only after the next block is mined. This is opposite to the way block number is incremented (prior to the next block/transaction).

I wouldn't call this a bug since the implementation matches the documented specification. Inconsistency would be a better term. Also, by applying this change, `block_info_generator.next_block` wouldn't have to be called in `__update_state` but before it (together with `__update_block_number`).

This would be a breaking change.

### Workaround
Create an empty block to force timestamp change right after calling set_time: [docs](https://github.com/Shard-Labs/starknet-devnet#create-an-empty-block)

**Comment by clexmond** [comment]
Additionally, for the RPC return values I believe the `timestamp` should be `accepted_time` to be in line with the expected return.

**Comment by FabijanC** [comment]
@clexmond I haven't checked, but maybe it's been addressed with this PR: https://github.com/Shard-Labs/starknet-devnet/pull/220 (merged but not yet part of a release)

**Comment by mikiw** [comment]
After talking, we decided that after set time or increase time new block should be generated (empty or with pending transactions in block-on demand-mode).

It will be the same behavior as in Hardhat.
![image](https://user-images.githubusercontent.com/5063930/222433294-1c521537-8982-441e-a097-535472b712b9.png)
