### ISSUE TITLE
Specify package version only in one place

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-devnet#223]
Currently we need to edit both `__init__.py` and `pyproject.toml` when bumping to a new version. Ideally there would be a single source of truth.

Doing [this](https://stackoverflow.com/questions/67085041/how-to-specify-version-in-only-one-place-when-using-pyproject-toml) works as expected on an installed instance of Devnet. However, the problem is with getting the version locally with poetry (`poetry run starknet-devnet -v`), which constantly gives me `0.2.1`, whereas I'd expect it to give `0.2.9` (correct version at the time of raising this issue).

**Comment by FabijanC** [comment]
Maybe `scripts/get_version.sh` can be dropped and our custom implementations of version extraction can be replaced with these:
```
poetry version
```
and
```
poetry run starknet-devnet --version
```

**Comment by mikiw** [comment]
So after a long debate about the pros and cons of [this](https://stackoverflow.com/questions/67085041/how-to-specify-version-in-only-one-place-when-using-pyproject-toml) solution, we decided to leave it as it is.
