### ISSUE TITLE
Declare tx signature type is int instead of hex-encoded string

### ISSUE THREAD

**Issue by Arcticae** [Shard-Labs/starknet-devnet#225]
**Describe the bug**
When querying the declare tx with signature, the return type is integer and not hex-encoded string (like in invoke)

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Send a signed declare tx
2. Wait for acceptance
3. Fetch the tx and get the signature

**Expected behavior**

**Devnet version**

- I am using Devnet version: 0.2.10
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**Machine specifications**

- OS: MacOS
- CPU: M1 Pro
- Memory: 16GB

**Comment by FabijanC** [comment]
Can declare transactions be signed using Starknet CLI? How are you signing them?

With some hacking in Starknet CLI, I got
```
BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.NON_EMPTY_SIGNATURE", "message": "The signature field in Declare transactions must be an empty list.\n0 != 2"
```

Is this issue a blocker for you?

**Comment by Arcticae** [comment]
No it's not a blocker - but it looks like it should be easily fixable, right? Since the expected return type is known from other endpoints

**Comment by FabijanC** [comment]
Sure it looks like it should be easily fixable, but I'm not able to reproduce it. How do I reproduce declare tx signing it with Starknet CLI and how are you doing it?

**Comment by mikiw** [comment]
@Arcticae Please, could you specify a detailed way how to reproduce this issue? What does this transaction look like and how is signed?

**Comment by Arcticae** [comment]
We use python (starknet.py) with native cairo-lang methods (`starkware.starknet.core.os.transaction_hash.transaction_hash.calculate_declare_transaction_hash`, and then `starknet_py.utils.crypto.facade.message_signature`)

**Comment by FabijanC** [comment]
I've tested this with Starknet CLI 0.10.0 which signs declare transactions. I tried getting fetching the transaction after declaration in Devnet v0.3.0 and it has hex strings as members of its signature list. If you can confirm that this is no longer an issue for you, we can close this. @Arcticae

**Comment by Arcticae** [comment]
Will tell the guys to test this one, thx!

**Comment by Arcticae** [comment]
@FabijanC this is no longer an issue - thanks!
