### ISSUE TITLE
Unification of --lite-mode

### ISSUE THREAD

**Issue by mikiw** [Shard-Labs/starknet-devnet#248]
As we discovered recently hashes for transactions are already in ```InternalTransaction```. It seems that specific flags in ```--lite-mode``` doesn't make much sense since it's hard to predict the future of optimizations.

We should stick only with one ```--lite-mode``` and adapt that to changes in starknet code.

TODO:
- Seems to be that ```InternalTransaction``` class already has a hash calculated to lite mode doesn't make sense anymore in this case. Are we removing ```--lite-mode-deploy-hash```?
- Change parameters of last PR https://github.com/Shard-Labs/starknet-devnet/pull/238 if we remove --lite-mode-deploy-hash, also remove other related tests
- Ask starknet team what can be optimized for testing purposes (maybe use weaker cryptography?)
- ```--lite-mode``` should be the default mode?
- ~~It would be nice to run profiling and check how to optimize the running of devnet, maybe there is something different than cryptography that we could focus on? (already done) #208~~

**Comment by mikiw** [comment]
Maybe it's possible to ask starkware team to provide parameters to disable transaction hash calculations or provide lite mode classes?

**Comment by FabijanC** [comment]
Related to one of the TODO points:
- #52 
- #208

**Comment by mikiw** [comment]
![image](https://user-images.githubusercontent.com/5063930/188389284-d4eb235a-e2f4-4859-89a6-d3a78adb6cbe.png)

**Comment by mikiw** [comment]
FAILED test/test_general_workflow.py::test_general_workflow[run_devnet_in_background1-0x2]
FAILED test/test_general_workflow_lite_block_hash.py::test_general_workflow_lite - Asserti...
FAILED test/test_postman.py::test_postman - FileNotFoundError: [Errno 2] No such file or d...
=================== 3 failed, 154 passed, 1 warning in 1850.10s (0:30:50) ===================

**Comment by mikiw** [comment]
So first PR is ready https://github.com/Shard-Labs/starknet-devnet/pull/249
