### ISSUE TITLE
Research if block hash can be deterministic for test purposes.

### ISSUE THREAD

**Issue by mikiw** [Shard-Labs/starknet-devnet#253]
Research if block hash can be deterministic for test purposes. If yes modify test_general_workflow with parameterized hash block.

**Comment by mikiw** [comment]
https://docs.starknet.io/docs/Blocks/header

**Comment by mikiw** [comment]
Yes, block hashes can be deterministic but 2 conditions need to be met:
- Timestamps need to be the same, so a new mechanism for that needs to be implemented to be machine independent in tests
-  Everything that requires salt (transactions, address in contract deploy, state) requires salt to be deterministic not random.

**Comment by mikiw** [comment]
The motivation of that task was to avoid this if in one test:
```
    # check if in lite mode expected block hash is 0x1
    if expected_block_hash == EXPECTED_SALTY_DEPLOY_BLOCK_HASH_LITE_MODE:
        assert_equal(expected_block_hash, get_block(parse=True)["block_hash"])
```
in
test_general_workflow.py

**Comment by FabijanC** [comment]
@mikiw Thanks for the research, closing then.
