### ISSUE TITLE
test_rpc_misc fails

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-devnet#257]
Appeared with #246 

State diff does not match. Perhaps the tx fails because of invalid program (incompatible after updating to 0.10.0)?

@drknzz

**Comment by drknzz** [comment]
It appears that the [previously referenced here](https://github.com/Shard-Labs/starknet-devnet/pull/242#discussion_r962648860) line is the problem, as without it the state diff is as it should be.

Once again, I do not know why it was there already in the first place when I started working on RPC, but probably just a bug.

**Comment by FabijanC** [comment]
Great! thanks for looking into this.
