### ISSUE TITLE
`estimate_fee` problem regarding 0.10 changes 

### ISSUE THREAD

**Issue by ivpavici** [Shard-Labs/starknet-devnet#266]
On starknet.js tests are failing with regards to `estimate_fee`

Starknet.js CI [throws](https://github.com/0xs34n/starknet.js/runs/8248623637?check_suite_focus=true):
`GatewayError: Invalid InvokeFunction: {'type': ['Unknown field.']}`

**Comment by FabijanC** [comment]
Closed via https://github.com/Shard-Labs/starknet-devnet/pull/268
