### ISSUE TITLE
get_block returns `state_root: ""` after initialization

### ISSUE THREAD

**Issue by amanusk** [Shard-Labs/starknet-devnet#269]
**Describe the bug**
get_block returns `state_root: ""` after initialization
This causes some frameworks to fail.

Running the script below on `starknet.py` returns an error:
``` 
File "/home/amanusk/Code/Cairo/ctf-lisbon/cairo-paradigm-ctf/venv-0.10/lib/python3.8/site-packages/starknet_py/net/schemas/common.py", line 49, in _deserialize
    return int(value, 16)
ValueError: invalid literal for int() with base 16: ''
```

In `0.2.1` the state root was non-empty and no error was caused

**Not reproducible on alpha-goerli**

- [X] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Install the latest version of `starknet-devnet`
2. Install the latest version of `starknet.py`
3. Run the script:

```
from starknet_py.net.networks import TESTNET
from starknet_py.net.gateway_client import GatewayClient


def main():

    port = 5050
    client = GatewayClient(f"http://127.0.0.1:{port}", TESTNET)
    print(client)
    block = client.get_block_sync(block_number=0)
    print(block)


if __name__ == '__main__':
    main()
```

**Expected behavior**
Get block #0 from the devnet

**Screenshots**
If applicable, add screenshots to help explain your problem. However, prefer providing copyable text.

**Devnet version**

- I am using Devnet version: 0.3.0

**System specifications**

- OS: Ubuntu
- CPU:
- Memory: 32GB
- Python version: 3.8

**Comment by amanusk** [comment]
Guess its a result of this.
Should it be `0x` ? 

https://github.com/Shard-Labs/starknet-devnet/blob/a0d2214898603fa122ce39d329088b946aff1b1f/starknet_devnet/blocks.py#L113

**Comment by FabijanC** [comment]
Thanks for the good bug report! You can test this via Devnet as a Docker container:
- instructions: https://github.com/Shard-Labs/starknet-devnet/#run-with-docker
- image: `shardlabs/starknet-devnet:01f82adb1df88c801adb5bf37bdb453321c5348e`
