### ISSUE TITLE
Feature request: add debug flag

### ISSUE THREAD

**Issue by JorikSchellekens** [Shard-Labs/starknet-devnet#273]
Currently running some heavy duty tests against the testnet and the process is getting killed regularly. It would be nice to be able to get more feedback on why a process was taking so long.

**Comment by FabijanC** [comment]
Is the existing Devnet log not enough? What would the proposed debug flag do?

**Comment by ivpavici** [comment]
Closed due to being superseded by https://github.com/Shard-Labs/starknet-devnet/issues/147
