### ISSUE TITLE
Publish github pages through CI/CD

### ISSUE THREAD

**Issue by ivpavici** [Shard-Labs/starknet-devnet#284]
@ivpavici will search and fix inconsistencies

**Comment by ivpavici** [comment]
Logo should also be available soon 👍 maybe a push to `gh-pages` will trigger a new build? I read something about this but I'm not sure... I can try that

**Comment by FabijanC** [comment]
Reminder: links need to be checked

**Comment by ivpavici** [comment]
Fixed inconsistencies, removed docs from readme.md... now it's left to update the pipeline to update the pages automatically when a change is pushed

**Comment by ivpavici** [comment]
example:
https://github.com/software-mansion/protostar/blob/master/.github/workflows/deploy_docs.yml
