### ISSUE TITLE
feat request: Built-in UDC contract

### ISSUE THREAD

**Issue by unparalleled-js** [Shard-Labs/starknet-devnet#296]
If this goes through: https://github.com/OpenZeppelin/cairo-contracts/pull/467,
it would amazing to have a UDC pre-deployed as part of Devnet for the purpose of deploying the first factory contract.
Then, all the rest of the deploys in the test suite can be from the factory contract. \

**Comment by 0xSidius** [comment]
https://github.com/OpenZeppelin/cairo-contracts/pull/467 UDC PR is about to be merged as it is: https://twitter.com/martriay/status/1578496057813528576

@FabijanC or @Nathan-SL could we have this in devnet as part of the 0.10.1 support release later this month?

**Comment by ivpavici** [comment]
Once these contracts are officially released (which will be any moment now), we can start working on support for it
