### ISSUE TITLE
Error message not returned for view functions

### ISSUE THREAD

**Issue by swapnilraj** [Shard-Labs/starknet-devnet#301]
**Describe the bug (observed vs expected behavior)**

The error message for a failing assert in a view function is not returned.

**Not reproducible on alpha-goerli**

- [X] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Compile and deploy this contract to the devnet
```
%lang starknet
@view
func f() {
  with_attr error_message("FAIL") {
    assert 1 = 0;
  }
  return ();
}
```
2. Call the function f

**Devnet version**

- I am using Devnet version: 0.3.1

**System specifications**

- OS: Macos
- CPU: ARM
- Python version: 3.9

**Comment by FabijanC** [comment]
Is this also present with Devnet 0.3.3?
