### ISSUE TITLE
DeployAccount does not save contract to self.contracts

### ISSUE THREAD

**Issue by war-in** [Shard-Labs/starknet-devnet#311]
**Describe the bug (observed vs expected behavior)**

I've tried to deploy an account through the `DeployAccount` transaction, but I can't call its functions.

I think the problem is in the `starknet_devnet.starknet_wrapper.StarknetWrapper.deploy_account` function.
In the `starknet_devnet.starknet_wrapper.StarknetWrapper.deploy` there is a 
![image](https://user-images.githubusercontent.com/61014013/196700364-c136ea65-b6f8-477b-8034-1efdce1bee05.png)
method used but in the`deploy_account` it is not.

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

Run devnet: `starknet-devnet --accounts=1 --seed=1`

Run the following script:
https://gist.github.com/war-in/41bc2ccdef697c55f4eda17f7e612b62

This is the `account_with_validate_deploy.cairo` file:
https://gist.github.com/war-in/e2d28c0a8c3f06dd70ae905b2b6905d1

**Devnet version**

- I am using Devnet version: v0.3.4
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS: macOS
- CPU: Apple M1 Pro
- Memory: 16 GB
- Python version: 3.9.13

**Comment by FabijanC** [comment]
Well you found the issue and the cause, not much left for me to do. But I can create a PR with a test so that this doesn't happen in the future.

**Comment by war-in** [comment]
Thank you very much 🙏
