### ISSUE TITLE
`/postman/load_l1_messaging_contract` POST fails on M1 mac

### ISSUE THREAD

**Issue by solimander** [Shard-Labs/starknet-devnet#315]
**Describe the bug (observed vs expected behavior)**

POST requests to `http://127.0.0.1:5050/postman/load_l1_messaging_contract` via `@shardlabs/starknet-hardhat-plugin` fail with the following error on an M1 Mac:

```
objc[84418]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[84418]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
[2022-10-20 12:15:34 -0600] [79459] [WARNING] Worker with pid 84418 was terminated due to signal 9
objc[84468]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[84468]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
[2022-10-20 12:15:35 -0600] [79459] [WARNING] Worker with pid 84468 was terminated due to signal 9
objc[84471]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[84471]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
[2022-10-20 12:15:35 -0600] [79459] [WARNING] Worker with pid 84471 was terminated due to signal 9
```

This error does NOT occur when running on Linux, tested with the `starknet-devnet` Linux docker image.

**Not reproducible on alpha-goerli**

- [X] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**
Steps to reproduce the behavior (M1 Mac only):

1. Clone `https://github.com/Shard-Labs/starknet-hardhat-example` and populate environment variables
2. Run `hardhat node` and `starknet-devnet --lite-mode` in different terminals
3. Run `npx hardhat test test/postman.test.ts --network localhost --starknet-network devnet`

**Devnet version**

- I am using Devnet version: v0.3.1
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS: macOS Monterey
- CPU: Apple M1 Max
- Memory: 64 GB
- Python version: 3.9.13

**Comment by FabijanC** [comment]
@Nathan-SL Can you reproduce this? And if you can, does any of the solutions from the link help?

**Comment by Nathan-SL** [comment]
@solimander @FabijanC I don't have this issue on my end. 
I tested it with
* OS: macOs Montrey
* CPU: Apple M1 Pro
* Python: v3.8.13

**Comment by solimander** [comment]
> @solimander Several solutions are listed here: https://github.com/rails/rails/issues/38560
> Does any of that help?

`export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` did the trick! May be worth adding as troubleshooting steps in the docs. Thank you!
