### ISSUE TITLE
Refactor predeployed contract wrapper classes

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-devnet#325]
UDC, FeeToken, Account (+ChargeableAccount) - these classes have common logic (namely the `deploy` method). They could use a common parent class.

**Comment by bigherc18** [comment]
```python
class Deployable:
    async def deploy(self) -> StarknetContract:
        raise NotImplementedError("")
```

The make `FeeToken`, `Account` and `UDC`inherit from it  

@FabijanC is this what this issue is about ? If so please assign it to me
