### ISSUE TITLE
UDC should be predeployed to the same address as on testnet

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-devnet#326]
The address where it is currently deployed was calculated with `deploy_from_zero=TRUE`, but seems like the salt also should have been set to 0.

I only learned about this after the release of Devnet v0.3.5. I would call this a bug, since the plan was for all UDCs to be at the same address: https://community.starknet.io/t/universal-deployer-contract-proposal/1864#deployment-5

**Comment by martriay** [comment]
I'm to blame. This was implied but not properly specified, sorry about that.

**Comment by FabijanC** [comment]
@martriay Well I am at least partly to blame :smiley: 
Anyway, my initial idea was to predeploy always to the same fixed address on Devnet. But I'm guessing that if devnet should follow testnet, it means that each time a new version of UDC is released, it will be deployed to a different address.
