### ISSUE TITLE
get_storage_at accepts key as hex

### ISSUE THREAD

**Issue by Solpatium** [Shard-Labs/starknet-devnet#329]
**Describe the bug (observed vs expected behavior)**

`get_storage_at` in devnet accepts key as hex or decimal string. The problem is that testnet/mainnet gateway only accepts decimal form. This causes a situation where some code using devnet with no issues might fail after switching to regular gateway API.

I checked the code and `key` param is accepted as as `custom_int` which allows for hex (https://github.com/Shard-Labs/starknet-devnet/blob/master/starknet_devnet/blueprints/feeder_gateway.py#L189).

There might be more cases like this, I am just reporting issue that we stumbled on.

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

Devnet
```
curl --request GET \
  --url 'http://127.0.0.1:5050/feeder_gateway/get_storage_at?contractAddress=0x04bb533aca25b0624a78fdc14a1a7412bc8768d967c01d12ab96ec4c1df411b9&key=0x1'
```

returns `0x0`

Gateway
```
curl --request GET \
  --url 'https://alpha4.starknet.io/feeder_gateway/get_storage_at?contractAddress=0x04bb533aca25b0624a78fdc14a1a7412bc8768d967c01d12ab96ec4c1df411b9&key=0x1'
```

returns 
```
{
	"code": "StarkErrorCode.MALFORMED_REQUEST",
	"message": "invalid literal for int() with base 10: '0x1'"
}
```

**Devnet version**

- I am using Devnet version: 0.3.3 (but same thing happens on 0.3.5)
- [x] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version: -

**System specifications**

- OS: Mac
- CPU: m1 pro
- Memory: 16GB
- Python version: 3.9

**Comment by mikiw** [comment]
The same problem is with:
- /get_block
