### ISSUE TITLE
Add a CLI parameter to specify if max_fee=0 is legal

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-devnet#342]
Currently max_fee can be 0 and tx will succeed (as documented). Regardless of what should be the default, this could be toggleable.

**Comment by ptisserand** [comment]
Hi, any idea about the flag name ?
- --max-fee-0
- --max-fee-none

Beside the flag name, I think I can work on this feature.

**Comment by FabijanC** [comment]
Hi, thanks for taking a look into this issue, there are three ways to implement this:
- Non-breaking:
  - The default remains the same - we allow txs with max fee set to 0
  - The potential flag we want to introduce would then prohibit such txs
- Breaking:
  - The default changes - we disallow txs with max fee set to 0
  - The potential flag would allow such transactions
- Breaking 2:
  - We don't introduce any flag, just disallow txs with max fee set to 0

We eventually want to stop supporting max fee == 0, but currently this might cause several tests to fail. Personally I'm leaning towards the second breaking option as I don't see much benefit from allowing such txs. What do you think?

**Comment by ptisserand** [comment]
My first thought was breaking option 1 since I don't get the point for transactions with max fee set to 0.
If such transactions are not needed, we should go to breaking 2.

**Comment by FabijanC** [comment]
@ptisserand Sorry for waiting, I asked people from StarkWare, waiting for their feedback.

**Comment by ptisserand** [comment]
Hi @FabijanC are you still waiting for feedback from StarkWare ?

**Comment by bbrandtom** [comment]
@FabijanC I think breaking option 1 is the way to go.
You generally want Devnet to behave as close as possible to the production StarkNet.
But I see a scenario where this feature might be helpful, so having a flag to allow it sounds like a good option.

**Comment by FabijanC** [comment]
Ok, @ptisserand, we can take the breaking option 1, thanks for the feedback everyone!

**Comment by ptisserand** [comment]
I'm wondering if we should check `max_fee` value in `/add_transaction` handler or in `StarknetWrapper` methods.
What do you think?

**Comment by ptisserand** [comment]
For flag name, are you ok with `--allow-max-fee-zero` ?

**Comment by FabijanC** [comment]
> For flag name, are you ok with `--allow-max-fee-zero` ?

Yes
