### ISSUE TITLE
Add version to RPC endpoint

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-devnet#343]
We would keep on supporting `/rpc`, but we would also support `/rpc/v0.2`.

Rationale: Pathfinder added this on their side and it will be simpler for client libraries not to have to implement logic on whether to include the version or not.

An open question is whether we should support both `v0.2` and `v0.3` when it's published.

@drknzz

**Comment by drknzz** [comment]
Supporting both versions would definitely facilitate the usage for user side.

We'll be assured once the next version actually releases and we see the scope of the changes.
For now though, I think both versions should most probably be supported.

**Comment by FabijanC** [comment]
Pathfinder supports v2 at `/` ([link](https://github.com/eqlabs/pathfinder/releases/tag/v0.4.0)), so this can be closed until further needed.
