### ISSUE TITLE
Support specifying chain ID

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-devnet#344]
Something like `starknet-devnet --chain-id <value>`, can be either hex or decimal

**Comment by mikiw** [comment]
We will use the name as a string to pass this configuration so it will be `MAINNET` or `TESTNET`.

Otherwise, we will get: `ValidationError: {'starknet_os_config': {'chain_id': ['Enum name must be string']}}`

```
        "starknet_os_config": {
            "chain_id": StarknetChainId.MAINNET.name, 
            "fee_token_address": hex(FeeToken.ADDRESS),
        },
```

**Comment by FabijanC** [comment]
Ok, perhaps the `StarknetChainId`  enum class can be used for input validation
