### ISSUE TITLE
FeeToken is not deployed

### ISSUE THREAD

**Issue by unparalleled-js** [Shard-Labs/starknet-devnet#346]
**Describe the bug (observed vs expected behavior)**

As of 0.4.0, I am not able to call any methods on the fee token contract.
Starknet does not recognize the address as containing any contract.

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Use starknet-devnet 0.4
2. Grab a contract using address from `from starknet_devnet.fee_token import FeeToken`
3. Call `get_code()` on it. Notice it errors.
4. Use starknet-devnet, notice it works.

Similarly, try to call `balanceOf` or `transfer` or any token method.. It works on `0.3.5` but `0.4` does not have a contract at that state.
   ...

**Devnet version**

- I am using Devnet version:
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS: macos
- CPU:
- Memory:
- Python version: 3.9 something

**Comment by FabijanC** [comment]
Can you show exactly how you are calling `get_code`, `balanceOf` and `transfer`?

The idea of this `starknet-devnet` is not to provide a Python library, but a web API.

Just a reminder that the devnet-specific way of getting the balance of an account is to do `GET /account_balance`. Similarly for minting: `POST /mint` (+ json args).
