### ISSUE TITLE
Improvement : add endpoint to return fork status

### ISSUE THREAD

**Issue by PhilippeR26** [Shard-Labs/starknet-devnet#347]
It could be useful to be able to request to devnet the fork info.
For example, with a such command :
`curl -X GET http://127.0.0.1:5050/fork-status -H "Content-Type:application/json"`
and have in return some infos :
- forked or not.
- source network of the fork (alpha-goerli, alpha-goerli2, alpha-mainnet, or URL).

**Comment by ptisserand** [comment]
Hi, can I work on this issue?

**Comment by FabijanC** [comment]
@ptisserand Yes you can! @ivpavici Do we have to do anything onlydust-wise?

 Although I believe first we would need to decide on the API. Here's my suggestion, let me know what you think:
- Introduce a new endpoint `/fork_status` (underscore to be in sync with other endpoints and the original gateway interface)
- If forking, it could return an object with (at least) two keys: forking url and forking block
- If not forking, it could return an empty object

You would need to create at least two tests (asserting response when forking and not)

**Comment by ptisserand** [comment]
@FabijanC I agree with your suggestion
For returned JSON object, is `{"url": "https://.....", "block": 437771}`  ok for you ?

**Comment by FabijanC** [comment]
Yeah, looks good!

**Comment by ivpavici** [comment]
@FabijanC we did not add any new tasks on OnlyDust, but we could I guess

**Comment by ptisserand** [comment]
For endpoint documentation, should I add it in `page/docs/guide/fork.md` ?

**Comment by FabijanC** [comment]
@ptisserand yes. You can also create a PR (or a PR draft) so we can discuss there
