### ISSUE TITLE
Cannot deploy an account in 0.4.1

### ISSUE THREAD

**Issue by filenko45** [Shard-Labs/starknet-devnet#351]
**Describe the bug (observed vs expected behavior)**

I start a devnet container using the latest-arm image and cannot deploy an account.

**Not reproducible on alpha-goerli**

- [+] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. docker run -d -p 127.0.0.1:5050:5050 shardlabs/starknet-devnet:latest-arm
2. starknet new_account --gateway_url=http://0.0.0.0:5050 --feeder_gateway_url=http://0.0.0.0:5050 --account=Acc
3. Mint to the account
4. starknet deploy_account --gateway_url=http://0.0.0.0:5050 --feeder_gateway_url=http://0.0.0.0:5050 --account=Acc
5. I get an error:

Got BadRequest while trying to access http://0.0.0.0:5050/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code":"StarknetErrorCode.UNDECLARED_CLASS","message":"Class with hash 0x1fac3074c9d5282f0acc5c69a4781a1c711efea5e73c550c5d9fb253cf7fd3d is not declared."}
.
Traceback (most recent call last):
  File "/Users/dev/cairo_venv/lib/python3.9/site-packages/services/external_api/client.py", line 117, in _send_request
    raise BadRequest(status_code=response.status, text=text)
services.external_api.client.BadRequest: HTTP error ocurred. Status: 500. Text: {"code":"StarknetErrorCode.UNDECLARED_CLASS","message":"Class with hash 0x1fac3074c9d5282f0acc5c69a4781a1c711efea5e73c550c5d9fb253cf7fd3d is not declared."}

Error: BadRequest: HTTP error ocurred. Status: 500. Text: {"code":"StarknetErrorCode.UNDECLARED_CLASS","message":"Class with hash 0x1fac3074c9d5282f0acc5c69a4781a1c711efea5e73c550c5d9fb253cf7fd3d is not declared."}

**Devnet version**

- I am using Devnet version: 0.4.1
- [+] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version: 0.4.0

**System specifications**

- OS: MacOS Monterey 12.6
- CPU: Apple M1
- Memory: 8
- Python version: 3.9

**Comment by FabijanC** [comment]
Which Starknet CLI are you using? `starknet --version`

**Comment by filenko45** [comment]
starknet 0.10.1

**Comment by FabijanC** [comment]
Not sure it will change anything, but can you try with starknet 0.10.2? You can try installing it in a separate [venv](https://docs.python.org/3/library/venv.html)

**Comment by FabijanC** [comment]
Also, I assume you have run `export STARKNET_WALLET=starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount`

**Comment by filenko45** [comment]
Updating the CLI to 0.10.2 helped. Thank you!

**Comment by FabijanC** [comment]
Ok to clear things up a bit:
- Devnet predeclares the account class used by Starknet CLI, but only does so for the account version used by the latest Starknet CLI
- In 0.10.1, the class hash of the class was `0x1fac3074c9d5282f0acc5c69a4781a1c711efea5e73c550c5d9fb253cf7fd3d`, in 0.10.2 (latest at the time of writing) it's `0x68cb33b3ab73ee34d2084cfcb7d07b24db48095ad0907c10b6fdb7b0e91ef0a`
