### ISSUE TITLE
Granular Block Generation Feature

### ISSUE THREAD

**Issue by EvolveArt** [Shard-Labs/starknet-devnet#361]
**Context**
Referring to the issue #163 and giving more precision our specific use case and reasoning behind it.

**Describe the bug (observed vs expected behavior)**

We're using hardhat plugin in order to run unit tests for Maker MCD on Starknet.
However, there is one contract that requires a parameter named `rho` to be updated to the latest timestamp in order to execute the `file` function ( see [here](https://github.com/makerdao/xdomain-dss/blob/add-end/src/Jug.sol#L117) )

However when running tests with `starknet-devnet` a new block is mined after each transaction is invoked, which is not the case in Foundry. Here is an example of a test we'd like to [reproduce](https://github.com/makerdao/xdomain-dss/blob/add-end/src/test/Jug.t.sol#L115). 

**Suggested Change**
We'd suggest to add a feature that a new block is only created on demand or when `starknet.devnet.setTime` is called. Thus, all transactions within will always run in a single block unless it's specified not too.

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**Devnet version**

- I am using Devnet version: 0.4.0
- [x] This happens with a dockerized Devnet (check the box if true).

**Comment by FabijanC** [comment]
I don't understand exactly what you are trying to achieve, but looks like you are depending on two separately issued transactions to be accepted in the same block. This cannot be guaranteed on other networks, like alpha-goerli - right? I mean, can't it happen even there, although rarely, that the two transactions are included in different blocks?

**Comment by EvolveArt** [comment]
> I don't understand exactly what you are trying to achieve, but looks like you are depending on two separately issued transactions to be accepted in the same block. This cannot be guaranteed on other networks, like alpha-goerli - right? I mean, can't it happen even there, although rarely, that the two transactions are included in different blocks?

So basically yes it would only be for devnet of course. And we would like to have some kind of feature that can be turned on such as new blocks are only created on demand within each test. Without that, what we have to do is manipulating time stamp after every transaction to make sure the next one doesn't fail which makes our tests unreadable.

**Comment by FabijanC** [comment]
Yes, I understand your feature request, just meant to say I don't understand the background (but I guess I don't have to understand the details of your project). We'll then try to prioritize this and #163 in the weeks to come.

**Comment by ivpavici** [comment]
@EvolveArt do you think we can track this task also with #163 ?

**Comment by EvolveArt** [comment]
> @EvolveArt do you think we can track this task also with #163 ?

I mean there are quite similar but this issue suggests a more granular feature. I guess you still can tho no worries!

**Comment by EvolveArt** [comment]
> Yes, I understand your feature request, just meant to say I don't understand the background (but I guess I don't have to understand the details of your project). We'll then try to prioritize this and #163 in the weeks to come.

Edited the issue the `here` link wasn't redirecting to the right line, sorry!

**Comment by mikiw** [comment]
This task should have a pre-task which is single block generation from many transactions. I'll start with that.
