### ISSUE TITLE
`NOT_RECEIVED` transaction receipt is inconsistent with testnet

### ISSUE THREAD

**Issue by cptartur** [Shard-Labs/starknet-devnet#366]
**Describe the bug (observed vs expected behavior)**

When trying to get a transaction receipt of an `NOT_RECEIVED` transaction, devnet returns responses like

```json
{
    "l2_to_l1_messages": [],
    "events": [],
    "transaction_hash": "0x0",
    "status": "NOT_RECEIVED"
}
```

when on testnet it is

```json
{
    "status": "NOT_RECEIVED"
}
```

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Run devnet
2. Try to get a transaction that wasn't received e.g. `GET /feeder_gateway/get_transaction_receipt?transactionHash=0x1`
3. Compare the result with `GET https://alpha4.starknet.io/feeder_gateway/get_transaction?transactionHash=0x1`

**Devnet version**

- I am using Devnet version: 0.4.2
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version: n/a

**System specifications**

- OS: MacOS
- CPU: M1 Pro
- Memory: 16 GB
- Python version: 3.9.12

**Comment by FabijanC** [comment]
Not able to reproduce this. Loaded http://127.0.0.1:5050/feeder_gateway/get_transaction?transactionHash=0x1 in my browser and got

```json
{ "status": "NOT_RECEIVED" }
```

**Comment by cptartur** [comment]
Double checked. It seems that responses are in fact correct. 

Either I was actually using some old version or, more likely, somehow mixed up get_transaction with get_transaction_receipt. Though I though I double checked that 😓 

Sorry for the confusion, closing the issue now.
