### ISSUE TITLE
Fix hex string validation

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-devnet#368]
I did some testing and looks like `custom_int` is the wrong validation approach since only hex strings (with or without the leading `0x`) are accepted by the sequencer API (no decimal strings as with `custom_int`). I don't know why it currently is like this in Devnet, there must have been a good reason for doing it this way.

A question is whether this resolving this should be considered a breaking change or a bug fix (for semver increment).

Also, in many places we simply do `int(value, 16)` which results in an Internal Server Error if it encounters an invalid value.

Not sure if it's a good idea, but we could replace all those occurrences with a new `validate_hex_string` which raises a `StarknetDevnetException` (and we already have a global handler for `StarkException` (parent of `StarknetDevnetException`) so it would be nicely handled).

**Comment by mikiw** [comment]
TODO:
- check all int(value, 16) occurrences in code

**Comment by mikiw** [comment]
Ok so in Alpha Goerli we can get block by hash that is starting with 0x
```
https://alpha4.starknet.io/feeder_gateway/get_block?blockHash=0x75e00250d4343326f322e370df4c9c73c7be105ad9f532eeb97891a34d9e4a5
```
and when we try to query it like this:
```
https://alpha4.starknet.io/feeder_gateway/get_block?blockHash=75e00250d4343326f322e370df4c9c73c7be105ad9f532eeb97891a34d9e4a5
```
we got:
```
{"code": "StarkErrorCode.MALFORMED_REQUEST", "message": "Block hash should be a hexadecimal string starting with 0x, or 'null'; got: 75e00250d4343326f322e370df4c9c73c7be105ad9f532eeb97891a34d9e4a5."}
```
Which I consider an expected behaviour and alignet in patterns in whole IT world.
