### ISSUE TITLE
StarkScan compatibility

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-devnet#369]
Copying from [Discord](https://discord.com/channels/793094838509764618/1054338698663186492)

> Starkscan has deployed https://devnet.starkscan.co/ to explorer the devnet [...]
> you can neither scan ETH ERC20 contract, nor scan the 10 pre-deployed  accounts.
> It could be useful if they are recorded in the first block, at launch.
> Not checked, but also probably the deployer.

**Comment by mikiw** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/5063930/219661796-6eeadd17-d737-4115-a204-c9033400c8f9.jpg)
The current state of the task.
