### ISSUE TITLE
Faulty RPC get_events parameter

### ISSUE THREAD

**Issue by penovicp** [Shard-Labs/starknet-devnet#382]
**Describe the bug (observed vs expected behavior)**

The RPC `get_events` method declaration doesn't conform to the specification, a single `filter` parameter should be used ([link](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L574)).

For the payload:
```
{
    "jsonrpc": "2.0",
    "method": "starknet_getEvents",
    "params": {
        "filter": {
            "from_block": "latest",
            "to_block": "latest",
            "chunk_size": 1
        }
    },
    "id": 0
}
```
- `testnet` replies with a successful response
- `devnet` replies with the error code `22` and message `"get_events() got an unexpected keyword argument 'filter'"`

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**Devnet version**

- I am using Devnet version: 0.4.4
- [x] This happens with a dockerized Devnet (check the box if true)

**Comment by mikiw** [comment]
Hi, @penovicp I'll take a look at it today. I remember that there were 2 versions and we implemented a newer one.

Related issue: https://github.com/Shard-Labs/starknet-devnet/issues/231

**Comment by jessupjn** [comment]
Any updates here?

**Comment by mikiw** [comment]
I'm on it, I have unfinished code on my local.
