### ISSUE TITLE
Change block creation API

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-devnet#385]
PR https://github.com/Shard-Labs/starknet-devnet/pull/374/files introduced `/create_block_on_demand`. Since we already had `/create_block` which is used for empty block creation, the naming may be **misleading**. We could do one of the following:

### 1. Have only one endpoint /create_block
- it would create an empty block if no txs in the mempool

### 2. Rename the endpoints
- E.g. `/create_empty_block` and `/create_block`

**Comment by FabijanC** [comment]
Leaning towards option 1. That single endpoint would then also be callable even when not running with `--blocks-on-demand` so that an empty block can be constructed.

**Comment by mikiw** [comment]
TODO: check if some tests needs to be removed
