### ISSUE TITLE
Make retries in forking mode configurable

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-devnet#396]
https://github.com/Shard-Labs/starknet-devnet/blob/94f8d5153b8851283eac3716e282d423875a3c59/starknet_devnet/devnet_config.py#L145

Supporting configurable retrying in forking mode would probably be as simple as replacing this hardcoded `n_retries=1` with something defined by the user on startup.

The user could specify this using `--fork-retry <NUMBER>` with the default value of 1.

**Comment by bigherc18** [comment]
I'd like to work on this issue
