### ISSUE TITLE
Change "StarkNet" to "Starknet"

### ISSUE THREAD

**Issue by ivpavici** [Shard-Labs/starknet-devnet#398]
Change the spelling of "StarkNet" from "StarkNet" to "Starknet" everywhere in the doc following the recommendations in [this SNIP](https://community.starknet.io/t/snip-naming-convention-starknet-not-starknet).

**Comment by Hug0x0** [comment]
I can stand on it 🫡  !
What do you think of changing the "StarkNet" in the python files? (ex: in the call.py files:  
    """
    Call a StarkNet function without creating a StarkNet transaction
    """ )

**Comment by Hug0x0** [comment]
Or only in the doc ?

**Comment by FabijanC** [comment]
> Or only in the doc ?

As pointed out on the PR, I think you should handle the python changes too.
