### ISSUE TITLE
Upgrade to poetry 1.3

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-devnet#405]
It failed when I tried: https://app.circleci.com/pipelines/github/Shard-Labs/starknet-devnet/1783/workflows/ae44501a-64b1-4d17-8f8f-bc420a8c3d5f/jobs/3818

Currently we're installing 1.2.1

Also, we have a Dockerfile which doesn't specify the version but just does `pip install poetry`

**Comment by cptartur** [comment]
It looks like a popular issue with circleci and poetry,

https://github.com/python-poetry/poetry/issues/7184

Using poetry with `--no-ansi` seems to be a working solution.

**Comment by FabijanC** [comment]
Thanks for researching!
