### ISSUE TITLE
Successfully deployed account to devnet but transaction failed because address not deployed 

### ISSUE THREAD

**Issue by ccsoloist** [Shard-Labs/starknet-devnet#431]
**Describe the bug (observed vs expected behavior)**

I create and deployed a new account on devnet, but failed to send transaction because `StarknetErrorCode.UNINITIALIZED_CONTRACT`.
**Not reproducible on alpha-goerli**

- [ ] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. `starknet new_account --gateway_url=http://127.0.0.1:5050 --account=dev`
2. `starknet deploy_account --gateway_url=http://127.0.0.1:5050 --account=dev`
3. `starknet declare --contract path_to_compiled_contract.json --gateway_url=http://127.0.0.1:5050 --account=dev`
   ...

**Devnet version**
alpha-goerli
- I am using Devnet version:
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS: MacOS 13.1
- CPU:
- Memory: 16G
- Python version: 3.9

**Comment by FabijanC** [comment]
Can you please provide your Devnet version and your starknet CLI version? You can obtain them with:
```
$ starknet-devnet --version
$ starknet --version
```

**Comment by ccsoloist** [comment]
> Can you please provide your Devnet version and your Starknet CLI version? You can obtain them with:
> 
> ```
> $ starknet-devnet --version
> $ starknet --version
> ```

starknet-devnet: 0.4.6
starknet: 0.10.3

**Comment by FabijanC** [comment]
My guess is that account deployment failed because the account address needs to be funded beforehand. I.e. after creating the account with `starknet new_account`, you get the address where it will be deployed with `starknet deploy_account`. Before actually running `starknet deploy_account` you need to give some token to that address, which you can achieve on Devnet by relying on minting: https://shard-labs.github.io/starknet-devnet/docs/guide/mint-token

**Comment by ccsoloist** [comment]
> Another thing, when you send a transaction, it is useful to check its status with
> 
> ```
> $ starknet get_transaction --hash <TX_HASH>
> ```
> 
> You could do this on the account deployment tx.

Thanks for the reply!

I ran the above command after running
```
starknet new_account --gateway_url http://127.0.0.1:5050 --account=dev4
starknet deploy_account --gateway_url http://127.0.0.1:5050 --account=dev4
```

and got 
```
{
    "status": "NOT_RECEIVED"
}
```

Is there anything wrong with my usage of the `new_account` and `deploy_account` command on devnet?

**Comment by FabijanC** [comment]
If you're getting `NOT_RECEIVED` then probably one of the following happened:
1. You restarted Devnet
2. You provided the wrong tx hash (be sure it's the hash printed as the transaction hash after running `starknet deploy_account`)

**Comment by FabijanC** [comment]
Starknet CLI thinks your deploy_account transaction was successful, that's why it thinks the account is already deployed (it's actually not). You can avoid getting the `Account ... already deployed` error by passing a force flag:
```
$ starknet deploy_account --force ...
```

**Comment by ccsoloist** [comment]
That worked for account deployment, thanks! But still failing on contract declaration 🤣

> 

```
starknet get_transaction --feeder_gateway_url http://127.0.0.1:5050 --hash 0x46b52c7e43230c0571b228356b78e378c9715953b838712f058c8179f80648
{
    "block_hash": "0x2e7000b7ef3ef5816212c550aa1a59fc2826fd0bc3fd621e02ff2bee4d94c04",
    "block_number": 5,
    "status": "ACCEPTED_ON_L2",
    "transaction": {
        "class_hash": "0x6f500f527355dfdb8093c7fe46e6f73c96a867392b49fa4157a757538928539",
        "constructor_calldata": [
            "0x7d34e699d0edc327c8ad30227c9ee7576d743d315c38590dc51090261210f19"
        ],
        "contract_address": "0x31757f498b24925814d1d0978f4141624ab830d017d3eb1167b9b94efd04d3b",
        "contract_address_salt": "0x2cb122984ae481d343d3c9519636b4d8cf394707dc38c135ab077e2a5a16ce2",
        "max_fee": "0x37c429987bffa",
        "nonce": "0x0",
        "signature": [
            "0x790d7436364d3922cb2b498078e7363305df4bc29771de0788ea6c12a6d2e7d",
            "0x7db325f6130e321621a36a23d3882e98d91eb61a8ebd00314bae6454f2fbb14"
        ],
        "transaction_hash": "0x46b52c7e43230c0571b228356b78e378c9715953b838712f058c8179f80648",
        "type": "DEPLOY_ACCOUNT",
        "version": "0x1"
    },
    "transaction_index": 0
}
```

```
starknet declare --contract compiled_contract.json --gateway_url http://127.0.0.1:5050 --account dev4
Got BadRequest while trying to access https://alpha4.starknet.io/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code": "StarknetErrorCode.UNINITIALIZED_CONTRACT", "message": "Requested contract address 0x31757f498b24925814d1d0978f4141624ab830d017d3eb1167b9b94efd04d3b is not deployed."}.
Traceback (most recent call last):
  File "/Users/ccsoloist/multichain/Starknet/multichain-contracts/env/lib/python3.9/site-packages/services/external_api/client.py", line 117, in _send_request
    raise BadRequest(status_code=response.status, text=text)
services.external_api.client.BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.UNINITIALIZED_CONTRACT", "message": "Requested contract address 0x31757f498b24925814d1d0978f4141624ab830d017d3eb1167b9b94efd04d3b is not deployed."}
Error: BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.UNINITIALIZED_CONTRACT", "message": "Requested contract address 0x31757f498b24925814d1d0978f4141624ab830d017d3eb1167b9b94efd04d3b is not deployed."}
```

**Comment by ccsoloist** [comment]
Ah it worked by replacing `gateway_url` with `feeder_gateway_url`

**Comment by FabijanC** [comment]
If you look at the error message, it says it failed while `trying to access https://alpha4.starknet.io/feeder_gateway/simulate_transaction`.

This happens if you don't specify a `--max_fee`. Starknet CLI attempts to estimate the max_fee by simulating the transaction. But this is done using the feeder_gateway and the default is probably alpha-goerli where your contract hasn't been deployed. So you should do one of the following:
1. Provide BOTH `--feeder_gateway_url` and `--gateway_url` (they can have the same URL)
2. Specify your own max_fee (something big)

**Comment by ccsoloist** [comment]
> If you look at the error message, it says it failed while `trying to access https://alpha4.starknet.io/feeder_gateway/simulate_transaction`.
> 
> This happens if you don't specify a `--max_fee`. Starknet CLI attempts to estimate the max_fee by simulating the transaction. But this is done using the feeder_gateway and the default is probably alpha-goerli where your contract hasn't been deployed. So you should do one of the following:
> 
> 1. Provide BOTH `--feeder_gateway_url` and `--gateway_url` (they can have the same URL)
> 2. Specify your own max_fee (something big)

Thanks! That finally makes sense.

Appreciate your help! 👍
