### ISSUE TITLE
`continuation_token` appears in response body after no events are left in `get_events` RPC function

### ISSUE THREAD

**Issue by tomek0123456789** [Shard-Labs/starknet-devnet#432]
**Describe the bug (observed vs expected behavior)**

The `get_events` method in RPC doesn't match the specification. Parameter `continuation_token` appears in response body after no events searched for are left. 

After deploying a cairo contract with code:
```
%lang starknet
%builtins pedersen range_check

from starkware.cairo.common.cairo_builtins import HashBuiltin

@storage_var
func storage(key: felt) -> (value: felt) {
}

@event
func put_called(key: felt, prev_value: felt, value: felt) {
}

@external
func put{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}(key: felt, value: felt) {
    let (prev_value) = storage.read(key);
    put_called.emit(key=key, prev_value=prev_value, value=value);
    storage.write(key, value);
    return ();
}
```
invoking `put` function 2 times and calling `get_events` in RPC with `"chunk_size": 4` the response looks like this:
```
{
    "id": 0,
    "jsonrpc": "2.0",
    "result": {
        "continuation_token": "1",
        "events": [
            {
                "block_hash": "0x06b0679b3060f2f1d02ec484f238f78a0a7c5aeb6bb0ced56edd40e8ddff05ff",
                "block_number": 3,
                "data": [
                    "0x01",
                    "0x00",
                    "0x01"
                ],
                "from_address": "0x021895a10d1f7319919b58967ec629d9fe6dc53269b0e24b8127ff4613759e55",
                "keys": [
                    "0x037e1449a2e98fcc818fa74e8abd5a3ebfefa48645be9b3777bd03e2c4ac54c0"
                ],
                "transaction_hash": "0x02304a74032d87b27f24537ae10105e29e014efb0fa9d0a9610132f490ac9373"
            },
            {
                "block_hash": "0x036f9108fb0b957df4d03eb18e7323c76c56219db854932a073d956ddba99347",
                "block_number": 4,
                "data": [
                    "0x02",
                    "0x00",
                    "0x02"
                ],
                "from_address": "0x021895a10d1f7319919b58967ec629d9fe6dc53269b0e24b8127ff4613759e55",
                "keys": [
                    "0x037e1449a2e98fcc818fa74e8abd5a3ebfefa48645be9b3777bd03e2c4ac54c0"
                ],
                "transaction_hash": "0x03037ea7104a49b4af996e0e3b21f886f1cd53c0742c8511d5f6ed2f553bec73"
            }
        ]
    }
}
```
Then, after adding `"continuation_token": "1"` to request body, the response looks like this:
```
{
    "id": 0,
    "jsonrpc": "2.0",
    "result": {
        "continuation_token": "1",
        "events": []
    }
}
```
I believe the problem lies [here](https://github.com/Shard-Labs/starknet-devnet/blob/v0.5.0a1/starknet_devnet/blueprints/rpc/misc.py#L155) and because [RpcEventsResult must return `continuation_token`, it isn't an optional parameter](https://github.com/Shard-Labs/starknet-devnet/blob/v0.5.0a1/starknet_devnet/blueprints/rpc/structures/responses.py#L79).

-----------------------------

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Deploy any contract on devnet with function that emits an event.
2. Call the function that emits an event, e.g. 2 times.
3. Call `get_events` function in RPC and follow the `continuation_token` parameter. 
4. `continuation_token` appears in response body even though it shouldn't.

**Devnet version**

- I am using Devnet version: 0.5.0a1
- [ ] This happens with a dockerized Devnet (check the box if true).

**Comment by FabijanC** [comment]
Thanks for the well-formulated issue! @mikiw I think the user has a point, can you take a look tomorrow?

**Comment by mikiw** [comment]
Thanks for reporting. I'll fix that.
