### ISSUE TITLE
How to connect to devnet?

### ISSUE THREAD

**Issue by sebastiendan** [Shard-Labs/starknet-devnet#45]
Hey,

README says
>Interact with Devnet as you would with the official Starknet [Alpha testnet](https://www.cairo-lang.org/docs/hello_starknet/amm.html?highlight=alpha#interaction-examples).

But how am I supposed to connect to my local/remote devnet? No args from the following list from `starknet --help` seem to actually redirect command executions to my devnet:

```
optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit
  --network NETWORK     The name of the StarkNet network.
  --network_id NETWORK_ID
                        A textual identifier of the network. Used for account management.
  --wallet WALLET       The name of the wallet, including the python module and wallet class.
  --no_wallet           Perform a direct contract call without an account contract.
  --account ACCOUNT     The name of the account. If not given, the default account (as defined by the wallet) is used.
  --account_dir ACCOUNT_DIR
                        The directory containing the account files (default: '~/.starknet_accounts').
  --flavor {Debug,Release,RelWithDebInfo}
                        Build flavor.
  --gateway_url GATEWAY_URL
                        The URL of a StarkNet gateway.
  --feeder_gateway_url FEEDER_GATEWAY_URL
                        The URL of a StarkNet feeder gateway.
```

**Comment by FabijanC** [comment]
Assuming you have a Devnet instance running, target it by adding the `--gateway_url <DEVNET_URL>` or `--feeder_gateway_url <DEVNET_URL>` to your starknet command.

E.g. if you ran `$ starknet-devnet` and got
```
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
```
Then to deploy a contract you run:
```
starknet deploy --contract <PATH> --gateway-url http://localhost:5000
```

For a better network user experience, assuming you can use a Node.js/npm environment, you can try `hardhat` with `starknet-hardhat-plugin` and have your custom networks defined in a configuration file, as documented [here](https://github.com/Shard-Labs/starknet-hardhat-plugin#testing-network).

**Comment by sebastiendan** [comment]
@FabijanC Indeed that was what I was trying and stopped at the account deployment which didn't seem to take my local container into consideration, which I understand now was not the right indicator as going further and deploying contracts clearly shows that my container is used. Thanks!

**Comment by Flydexo** [comment]
In my case even if I provide a gateway_url or feeder_gateway_url for every command I get this error:
`Consider passing --network or setting the STARKNET_NETWORK environment variable.`

**Comment by FabijanC** [comment]
@Flydexo Can you show the exact command you are executing?

**Comment by Flydexo** [comment]
It was a problem on my side with the virtual envs. Fixed 👍
