### ISSUE TITLE
`invoke`/`call` fail finding the contract to call and return different parsed contract addresses

### ISSUE THREAD

**Issue by sebastiendan** [Shard-Labs/starknet-devnet#47]
Hey,

When trying to `invoke` or `call` a function of my contract, I get errors when finding the contract referenced with `--address`:

```
starknet call --address 0x0180187d947f45e66a0b049422b9bc9673a11b7a8320daad28bdf247e7d28328 --abi contract_abi.json --function get_balance --gateway_url http://52.179.101.122:5000
```

returns

```
Got BadRequest
Traceback (most recent call last):
  File "/Users/sebastiendan/cairo_venv/lib/python3.9/site-packages/services/external_api/base_client.py", line 116, in _send_request
    raise BadRequest(status_code=response.status, text=text)
services.external_api.base_client.BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.UNINITIALIZED_CONTRACT", "message": "Error at pc=0:13:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:467)\nUnknown location (pc=0:436)\n\nError in the called contract (0x180187d947f45e66a0b049422b9bc9673a11b7a8320daad28bdf247e7d28328):\nContract with address 0x180187d947f45e66a0b049422b9bc9673a11b7a8320daad28bdf247e7d28328 is not deployed."}
Error: BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.UNINITIALIZED_CONTRACT", "message": "Error at pc=0:13:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:467)\nUnknown location (pc=0:436)\n\nError in the called contract (0x180187d947f45e66a0b049422b9bc9673a11b7a8320daad28bdf247e7d28328):\nContract with address 0x180187d947f45e66a0b049422b9bc9673a11b7a8320daad28bdf247e7d28328 is not deployed."}
```

=> The  `0x180187d947f45e66a0b049422b9bc9673a11b7a8320daad28bdf247e7d28328` address displayed in the error message defers from the one referenced in the call (`0x0180187d947f45e66a0b049422b9bc9673a11b7a8320daad28bdf247e7d28328`).

---

```
starknet invoke --address 0x0180187d947f45e66a0b049422b9bc9673a11b7a8320daad28bdf247e7d28328 --abi contract_abi.json --function increase_balance --inputs 1234 --gateway_url http://52.179.101.122:5000
Invoke transaction was sent.
Contract address: 0x0180187d947f45e66a0b049422b9bc9673a11b7a8320daad28bdf247e7d28328
Transaction hash: 0x30261268712fc763f4b7bbefe24920853f98a20da32c340567a3b973e2ba4ee
```

leads to

```
starknet tx_status --hash 0x30261268712fc763f4b7bbefe24920853f98a20da32c340567a3b973e2ba4ee --feeder_gateway_url http://52.179.101.122:5000
{
    "tx_failure_reason": {
        "code": "TRANSACTION_FAILED",
        "error_message": "No contract at the provided address (0x039159e62d9936e67b2adb434aeab1201965bd7c3342e48a0cc6345d2a86ba87).",
        "tx_id": "0x030261268712fc763f4b7bbefe24920853f98a20da32c340567a3b973e2ba4ee"
    },
    "tx_status": "REJECTED"
}
```

This time the address displayed in the error message is `0x039159e62d9936e67b2adb434aeab1201965bd7c3342e48a0cc6345d2a86ba87`.

**Comment by sebastiendan** [comment]
Feel free to use my test gateway at `http://52.179.101.122:5000`.

**Comment by FabijanC** [comment]
Hi, thanks for providing your gateway, pretty cool to be testing on something other than localhost.

I'm suprised that your `starknet call` command works because it expects `--feeder_gateway_url` to be provided and you are providing `--gateway_url`.

Does your contract do any calling by proxy? Also, is your `STARKNET_WALLET` environment variable set by any chance? If so, either unset it or use the `--no_wallet` flag with Starknet CLI commands.

**Comment by FabijanC** [comment]
Also, if I may guess, you aren't using the latest version of devnet. The latest version (0.1.17) offers dumping/loading with which you can dump a devnet instance set up with an account and load it whenever you want.

**Comment by sebastiendan** [comment]
> Also, if I may guess, you aren't using the latest version of devnet. The latest version (0.1.17) offers dumping/loading with which you can preserve a devnet instance set up with an account and load it whenever you want.

I'm using docker. I will the latest image.

**Comment by sebastiendan** [comment]
>Regarding your original issue, did using the --no_wallet flag help? Or running unset STARKNET_WALLET?

Yes, that was it! Can you explain why I needed not to use a wallet?

**Comment by sebastiendan** [comment]
I can see my transactions are not moving passed the "ACCEPTED_ON_L2" status. Is this because it is outside the scope of the devnet to actually communicate with Starkware's STARK prover?
