### ISSUE TITLE
UI Explorer

### ISSUE THREAD

**Issue by dmpierre** [Shard-Labs/starknet-devnet#51]
Hello :)

Do you think developing an UI around starknet-devnet would be interesting for the project? This would make it easy to explore transactions and contracts deployed easily.

Asking since I could spend some time on that feature, I want to be sure that it would be relevant to this use case!

**Comment by FabijanC** [comment]
Hi, thanks for sharing this idea, it looks useful. I've been told that Nethermind are working on bringing `starknet-devnet` to [Voyager](https://voyager.online/), which might just be what you are suggesting. I've asked for their status and will post it here once I get it.

**Comment by Scooletz** [comment]
Hey @dmpierre I'm not sure if I do understand your question right, but recently we provided a local version of Voyager that you can pull and run as a docker image. It's provided at https://github.com/DemerzelSolutions/voyager/pkgs/container/voyager and we'll be sharing news soon. Let me know if this is sth you've been looking for.

**Comment by dmpierre** [comment]
Perfect thanks, will use this :)
