### ISSUE TITLE
A list of pre-funded test accounts

### ISSUE THREAD

**Issue by unparalleled-js** [Shard-Labs/starknet-devnet#55]
## Feature Request

To have a list of pre-populated accounts the same as ganache of Hardhat node does.

Bonus if we can have a single key, like HD-Path style, be the source of generating all of them.

## Questions

Is this possible to do?
Is it wise to do?

## Disclaimer

I am still getting used to these ZK rollup style ecosystems.
My perspective is a builder who needs to make tooling for Starknet and needs it to be roughly compatible / similar to other existing Python Ethereum tooling.

**Comment by FabijanC** [comment]
Hi, thanks for the proposal, seems like a good feature request! I am almost sure it is possible, but don't understand why it wouldn't be wise?

**Comment by unparalleled-js** [comment]
Does Starknet have the concept of a genesis file? I have noticed that there is not a genesis block.

> but don't understand why it wouldn't be wise?

The only reason I can think of why it wouldn't be wise would be that the process of generating (+ deploying?) the accounts would take a long time. I am still figuring out how Starknet works!

**Comment by FabijanC** [comment]
> The only reason I can think of why it wouldn't be wise would be that the process of generating (+ deploying?) the accounts would take a long time. I am still figuring out how Starknet works!

Well the user could specify the number of accounts to be predeployed, so it would lonly take a long time of you want it. What also might be useful for the described use-case is devnet dumping and loading: https://github.com/Shard-Labs/starknet-devnet#dumping
