### ISSUE TITLE
Setup Voyager local to point to devnet

### ISSUE THREAD

**Issue by ccarnino** [Shard-Labs/starknet-devnet#60]
Hello team, 
I tried to run the voyager-local as described here https://voyager.online/local-version/ but it's lacking the info about how to point it to the currently running devnet on the same machine.

Maybe it's just me not being prepared enough on Docker, but can you help with the launch command for the docker voyager-local?

Thanks a lot!

**Comment by FabijanC** [comment]
Hi, thanks for the issue.

@badurinantun Could we expand our Readme section on this?

**Comment by ccarnino** [comment]
Thanks but I am out of my element with docker. And I am trying to juggle already 3 different problems at the same time 😄

**Comment by FabijanC** [comment]
Apparently this cannot be setup, as noted here: https://discord.com/channels/793094838509764618/960813841103593502

Why so?
> because to run an instance of voyager you have to input a L1 rpc node with a starknet core contract that would need to verify L2

This can't be reproduced with Ganache and mock of core contract?
> In theory yes but I assume that you'd have to send the L2 proofs to the ganache L1
