### ISSUE TITLE
Deploy argent-x wallet contract

### ISSUE THREAD

**Issue by CondeGil** [Shard-Labs/starknet-devnet#68]
Hey there,
I'm trying to deploy an argent-x wallet contract and get this strange error:
`
TRANSACTION_FAILED: Illegal method selector: 215307247182100370520050591091822763712463273430149262739280891880522753123.
`
To be honest I dont know if this is an issue on devnet side or on argent-x (although it deploys fine in testnet/mainnet) or even starknetjs.
And might even be a known issue. I thing this issue is on argent-x github as well but had receive no attention. Do you have any information regarding this?

**Comment by FabijanC** [comment]
Hi, thanks for reporting this here. Can you link the related argent-x issue here? This might be related to the way default entrypoint is targeted on devnet. Will try to address it this week.

**Comment by CondeGil** [comment]
Sure, there you have it: [https://github.com/argentlabs/argent-x/issues/417](https://github.com/argentlabs/argent-x/issues/417)

**Comment by FabijanC** [comment]
Working on it... more news very soon
