### ISSUE TITLE
Feature request: Set block timestamp for testing purpose.

### ISSUE THREAD

**Issue by abdelhamidbakhta** [Shard-Labs/starknet-devnet#94]
It would be really useful to be able to set block timestamp for testing purpose.
Currently it is really hard to test smart contracts that use `get_block_timestamp` because we don't have a way to mock the value in order to test different scenario.

Having this ability would help a lot. If you use `protostar` it is possible to mock block timestamp using [warp](https://docs.swmansion.com/protostar/docs/tutorials/guides/testing#warp) cheat code.
But if you use `nile` it is not possible to do the same because they use `starknet-devnet`.

**Comment by FabijanC** [comment]
Thanks for the suggestion, this is under development.
